import esbuild from "esbuild";
import { copyFileSync, mkdirSync, rmSync } from "node:fs";
import process from "process";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const OUTDIR = "dist";

// The shippable plugin folder: what a user drops into
// <vault>/.obsidian/plugins/sentilis/, and what release.yml zips. LICENSE
// travels with it because main.js bundles the AGPL-licensed Sentilis SDK,
// so the artifact is a combined work under those terms.
const PLUGIN_ASSETS = ["manifest.json", "styles.css", "LICENSE"];

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
	],
	// Node builtins are deliberately NOT externalized, and `platform` is
	// deliberately left at its "browser" default. manifest.json declares
	// isDesktopOnly: false, so this bundle has to load on mobile where
	// there is no Node runtime. Marking builtins external would let a
	// `node:fs` import slip through as a require() that throws only on a
	// phone; leaving them unresolvable turns the same mistake into a build
	// error here. scripts/check-mobile-safe.mjs backstops the artifact.
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	// Production builds go to dist/ alongside the rest of the plugin files.
	// Watch mode keeps writing main.js at the repo root: development happens
	// through a symlink of this repo into the vault's plugins folder (see
	// README), where Obsidian expects main.js next to manifest.json.
	outfile: prod ? `${OUTDIR}/main.js` : "main.js",
	minify: prod,
});

if (prod) {
	rmSync(OUTDIR, { recursive: true, force: true });
	mkdirSync(OUTDIR, { recursive: true });

	await context.rebuild();

	for (const asset of PLUGIN_ASSETS) {
		copyFileSync(asset, `${OUTDIR}/${asset}`);
	}

	process.exit(0);
} else {
	await context.watch();
}
